CREATE TABLE IF NOT EXISTS auto_post (
    id SERIAL PRIMARY KEY,
    auto_user_id INT NOT NULL REFERENCES auto_user(id) ON DELETE CASCADE,
    description VARCHAR(1000) NOT NULL,
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);